### ISSUE TITLE
Database imports

### ISSUE THREAD

**Issue by Drag0nB0i** [lexogrine/hud-manager#14]
Hey! So ive been using the manager for a little and I need some help!   I have imported a Database file and it wasn't correct.  So we corrected it and now it is not changing.  Is it a problem with my file or is it just not changing in the HUD manager?  Thanks!

**Comment by osztenkurden** [comment]
Hi @Drag0nB0i, which version do you use? In 1.2 we updated the way imports work

**Comment by Drag0nB0i** [comment]
> Hi @Drag0nB0i, which version do you use? In 1.2 we updated the way imports work

Ohhh I just checked, I have 1.1 downloaded. Did you release an update yesterday?

**Comment by osztenkurden** [comment]
@Drag0nB0i Yes. Now if the import will detected conflict (the same id for entries) it will inform you, and will allow you to cancel or overwrite changes

**Comment by Drag0nB0i** [comment]
> @Drag0nB0i Yes. Now if the import will detected conflict (the same id for entries) it will inform you, and will allow you to cancel or overwrite changes

Got it! Thank you so muchh!! <3
