### ISSUE TITLE
Hud changes not saved

### ISSUE THREAD

**Issue by kkuez** [lexogrine/hud-manager#16]
When customizing a loaded HUD (Your stated example in this case) and adding changes, f.e. pictures to boxes or changing text in the trivia boxes, theses changes will be rendered.

Though when restarting the hud-manager those changes will be gone.

Is this a bug?
As a user im expecting changes to last.

Last windows updates
Last installer of hud-manager from today

**Comment by osztenkurden** [comment]
It is not a bug - for now per-HUD config changes are not saved between HUD Manager restarts, however that will change in the future release.

**Comment by osztenkurden** [comment]
In +1.3.1 versions settings are now stored between restarts.
