### ISSUE TITLE
A JavaScript error occurred in the main process / Can't add new HUD

### ISSUE THREAD

**Issue by GoRnoStayStandin** [lexogrine/hud-manager#18]
With first start I have this message:
![error](https://user-images.githubusercontent.com/57696403/87845856-e1df2480-c8fd-11ea-9276-81e34e7e34f2.jpg)

Also I can't add any HUD to the HUD Manager

**Comment by osztenkurden** [comment]
This happens when server isn't killed properly - for now try restarting PC and running Manager with admin privileges

**Comment by GoRnoStayStandin** [comment]
The error disappeared, but I still can't add new HUD

**Comment by GoRnoStayStandin** [comment]
Ok, that was my problem. Sorry
