### ISSUE TITLE
Last round of half and game will store win_type and winner incorrectly

### ISSUE THREAD

**Issue by Barsnes** [lexogrine/hud-manager#30]
A typical round would be stored in the API wtih all the information needed, however for the last round of the half, and last round of the game, the `winner` and `win_type` are stored as nulls. This is consistent throughout all demos I've tested with

correct:
```
           "round": 1
            "players": {
              "76561198130490651": {
                "kills": 1,
                "killshs": 1,
                "damage": 77
              }, { ... }
            },
            "winner": "T",
            "win_type": "elimination"
          },
``` 

incorrect:
```
           "round": 15
            "players": {
              "76561198130490651": {
                "kills": 1,
                "killshs": 1,
                "damage": 77
              }, { ... }
            },
            "winner": null,
            "win_type": null
          },
```

**Comment by osztenkurden** [comment]
It seems like its the way demos are saved - some config system (ex ESEA) makes demos not sending the same data as on live matches, therefore making demos unusable. I will look into it though

**Comment by Barsnes** [comment]
> It seems like its the way demos are saved - some config system (ex ESEA) makes demos not sending the same data as on live matches, therefore making demos unusable. I will look into it though

I've done some testing and it seems like it's because of the way eBot sends data and ends round 15 and the last round
