### ISSUE TITLE
Save last gamestate data on mapEnd = true

### ISSUE THREAD

**Issue by Barsnes** [lexogrine/hud-manager#31]
Lexogrine should take the last gamestate data for a map when `mapEnd = true`
This will make it easier to create post match scoreboards, graphs, etc.

I think the last gamestate should be saved to `/api/match/` and then under `match.vetos.[map].game`

**Comment by osztenkurden** [comment]
The finished map will hold `CSGO` object from `csgogsi` package as `game` property in 1.12
