### ISSUE TITLE
Save playerdata to match

### ISSUE THREAD

**Issue by Barsnes** [lexogrine/hud-manager#38]
I think that saving all playerdata when the match ends will make it easier to process data after the macth is finished.

Right now you only get the steam id of a player, given under `/api/match/` and then in `vetos[x].rounds[x].players` - If things such as name and team is stored somewhere on the map, or under each player for each round, it will make it easier to later process the data in a third-party application.

**Comment by osztenkurden** [comment]
Will be added in 1.12 as part of fix of #31
