### ISSUE TITLE
Country Flag

### ISSUE THREAD

**Issue by benten2411** [lexogrine/hud-manager#5]
Many flags do not appear in this HUD (Player + Team). How to fix it?

**Comment by bibinguyen** [comment]
hud-manager use country list from react-select-country-list so Việt Nam label default is "Viet Nam", but image file is Vietnam.png
Just rename Vietnam.png to Viet-Nam.png (default image format for country label with space), and rebuild.

**Comment by osztenkurden** [comment]
@benten2411 This one is actually mapping issue in the github.com/lexogrine/csgo-react-hud repository. I'm fixing this as we speak, but if you could send list of countries you found are missing pictures, that would speed up the process.
