### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Honygx** [lexogrine/hud-manager#58]
Hey guys, I have a problem wit hud. After update to newest version I can't place hud on screen. It always start as a black screen in background and I tried everything to fix it, but nothing worked, dunno what to do else. Can you please help me somehow´? Thanks a lot.

**Comment by osztenkurden** [comment]
Usually it is issue with Windows settings. It's a known issue, and I'm trying to find the source of it. While I still haven't found a solution you can try looking into the Embedded HUD system. It doesn't use overlays, so it would work more consistently

**Comment by Honygx** [comment]
Thank you, I'll try it and brick a lack with solving a problem:)

**Comment by osztenkurden** [comment]
@Honygx Hi! Our community might have found fix to this, in Windows  settings this must be set to off:
![image](https://user-images.githubusercontent.com/25458209/112799474-b0af1a80-906e-11eb-8d55-4175f1f4d6ad.png)
Let us know if that resolves the issue :)

**Comment by Honygx** [comment]
@osztenkurden Yo, thanks for this information, the pc from where we observing CS we also use for streaming LoL and they need to taskbar to hide, so I turned it off and it helped in way that it now shows HUD, but in background and I tried everything what I could do to put it on foreground, but nothing helped. Anyway, the embedded HUD working perfectly, so we may use this one in future, 'cause we play on private servers so it doesn't affect anything. Thank you for your patience:)

**Comment by osztenkurden** [comment]
@Honygx Usually alt tabing to something else than LHM, then to CS:GO, and then to HUD works when its in the background. Anyway, glad to know you got it working! <3
