### ISSUE TITLE
"GAMESTATE INTEGRATION: FILE COULDN'T BE FOUND" and "CONFIGS: FILES ARE MISSING"

### ISSUE THREAD

**Issue by Sas0ni** [lexogrine/hud-manager#64]
https://i.gyazo.com/4fe64a7d3fdbfd6606f73c1611d2bdcd.png

This error just comes up when i try to add GSI Files and add config files

**Comment by osztenkurden** [comment]
Was fixed in dms, will be fixed in the next update
