### ISSUE TITLE
HUD loading in seperate window?

### ISSUE THREAD

**Issue by wixinho** [lexogrine/hud-manager#65]
Cant seem to load the Lexogrine HUD when In-game. It seems to be loading the HUD in a seperate window. Any fix?

**Comment by osztenkurden** [comment]
Well, that's how basic HUD overlaying works, so there's nothing to fix. You need to have CS:GO opened in Fullscreen Windowed mode so another window can go on top of it. It is however possible to add HUD directly to the game, but you need to start game with HLAE, which adds -insecure flag to your launch options. We call it "Embedded mode" (we used to call it AFX Mode) and you can find tutorial on this here: https://www.youtube.com/watch?v=s-yy_XoNLWE
