### ISSUE TITLE
Dark window in hud manage

### ISSUE THREAD

**Issue by Perekos** [lexogrine/hud-manager#66]
Hello everyone, who can help me how can fix this is?
This problem appeared a long time ago, I cannot imagine what it could be connected with.
I set up the program using videos from YouTube, but all the time I run it, a dark screen appears.
![image](https://user-images.githubusercontent.com/71025305/118295102-26b6f600-b4e4-11eb-82ee-47491f32b83a.png)

**Comment by kherchel** [comment]
Hi! For support please join the official Lexogrine HUD Manager Discord server at https://discord.com/invite/CHrg33UMs3

**Comment by Perekos** [comment]
kherchel, thank you

**Comment by osztenkurden** [comment]
Additionally: https://github.com/lexogrine/hud-manager/issues/58
