### ISSUE TITLE
Autologin

### ISSUE THREAD

**Issue by kubo6472** [lexogrine/hud-manager#82]
Allow for discord inspired authentication between app and the website.

**Comment by osztenkurden** [comment]
How would that work in your proposal? Doing things with QR code would kinda not work, given that we don't provide mobile app of any kind

**Comment by kubo6472** [comment]
Not with the mobile app. When you install the desktop applicaiton for the first time, and open it, it opens up a call into the browser to login automatically.

**Comment by kubo6472** [comment]
It is formatted like this: 
https://discord.com/handoff?rpc=1234&key=12345678-1234-5678-1234-1234567812345678

**Comment by kubo6472** [comment]
If a person logs in on the lhm.gg website, then opens the app for the first time, it will open a website like: https://lhm.gg/handoff?rpc=1234&key=12345678-1234-5678-1234-1234567812345678 and log the user in automatically.
