### ISSUE TITLE
Minimap bug

### ISSUE THREAD

**Issue by GoRnoStayStandin** [lexogrine/hud-manager#9]
![image](https://user-images.githubusercontent.com/57696403/85517163-95236900-b631-11ea-9955-be07d44e399f.png)
Is there any way to fix BO5 maps under the map?
![Без имени-1](https://user-images.githubusercontent.com/57696403/85517527-edf30180-b631-11ea-8976-02fa36fb9d51.png)

**Comment by osztenkurden** [comment]
@GoRnoStayStandin Can you show me the veto page from the Manager of this match please?

**Comment by GoRnoStayStandin** [comment]
![image](https://user-images.githubusercontent.com/57696403/85585159-58c42d00-b672-11ea-8169-b11fdb549a31.png)
Do you mean this?

**Comment by osztenkurden** [comment]
@GoRnoStayStandin Thank you, I will update the HUD ASAP.
