### ISSUE TITLE
Team auto switching randomly & breaking HUD

### ISSUE THREAD

**Issue by HiyaNoot** [lexogrine/hud-manager#97]
![Screenshot (278)](https://user-images.githubusercontent.com/107059212/173881666-b9f896a2-521c-432b-ae52-55cabd1d518b.png)

I am seeming to have an issue where during a random round, the HUD switches the teams to the wrong side (CT -> T, T -> CT)
This goes back and forth for a few seconds, as the teams switch
The end result is that the HUD shows the wrong team, and breaks players (not observed player)

I am still having issues when teams don't switch after the half, and I have to change it manually, as well as the series points

This problem has started to become more frequent for me, and I have used the same HUD in the past, without any issues

(This is a custom HUD, using the react-hud as a base platform to build on)

**Comment by osztenkurden** [comment]
Do you have auto-switch turned off or on in the settings?

**Comment by HiyaNoot** [comment]
I've had it "on" for months, but teams never switched, so I had to do switch team sides manually (still don't know if this function was broken)
As of a recent update, the team's would switch but switch multiple times during a round (auto-switch was "on")
I turned it "off" during the game, but I couldn't fix the CT and T colours after they switched, thusly completely breaking

The mapseries score board also broke, showing scores like 1:11:16 due to the teams switching back and forth

I shall try find a clip, where the issue arose

**Comment by osztenkurden** [comment]
You should keep Auto switch turned off, we are redoing this feature.

Regarding team switch at half, issue is more complicated. CS:GO sends wrong data after side switch when default HUD is turned off. They fix a bit themselves after you manually switch observed player. If teams are reversed after that, you should just click Alt+R.

Also I advise against any config that switch teams (left to right and vice versa) after the half, simply because its confusing for the observer.

**Comment by HiyaNoot** [comment]
Avatars not rendering + teams on wrong side (switching teams during round)
https://clips.twitch.tv/CooperativeCulturedFiddleheadsTTours-Q8U178s1kZn_T0EJ

Auto-switch off (manually changed sides) + breaks HUD
https://clips.twitch.tv/SarcasticSparklyPterodactylHumbleLife-89NDGUTITuQ-3-Xr

The base HUD is based on the CSGO react hud, where I only tweaked the visuals
